### PR TITLE
Add libmysqlclient-dev package for cluster feature

### PR DESCRIPTION
**Pull request by someone1**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks for the PR, but why only x86? Why is it the dev package? Please provide more info on why it's needed and provide some links if necessary.

**Comment by someone1** [comment]
It's just what the message says on the cluster admin page:

image


It is also mentioned [here](https://openvpn.net/vpn-server-resources/configuration-database-management-and-backups/#change-database-backend-to-mysql-or-amazon-rds):

> You will need at minimum mysql-client package installed on your system, and in some cases libmysqlclient-dev as well.

It looks like you may need the dev package to use the migration tool, but you might be able to get away with the `libmysqlclient20` package along with the standard `mysql-client` package instead.

**Comment by aptalca** [comment]
Ignore my comment about x86 only before, I was having a senior moment and thought this was multi-arch, but it's not.

Thanks for the update, we'll look into it.

**Comment by aptalca** [comment]
@someone1 
I did some test and the regular mysql-client package is not sufficient. It specifically needs the libmysqlclient-dev.

I will actually lump this in with a big rewrite to fix breaking updates, so I'll close this PR. If you'd like to get the commit credit, please PR to the rewrite branch here: https://github.com/linuxserver/docker-openvpn-as/blob/rewrite/Dockerfile

And keep in mind that the packages are listed in alphabetical order, so add it under iptables.

Thanks

**Pull request closed without merging**
